# Generated by Django 5.1.2 on 2024-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.IntegerField()),
                ("phone", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
